title: My awesome BLOG!
theme: minima
author: faust87
email: faust8687@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome BLOG! Is it so easy to do this?! Fantastic!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
